export type RenderableCssProperty = 'color'
    | 'background'
    | 'background-color'
    | 'border'
    | 'border-width'
    | 'border-style'
    | 'border-color'
    | 'border-radius'
    | 'border-top-left-radius'
    | 'border-top-right-radius'
    | 'border-bottom-left-radius'
    | 'border-bottom-right-radius'
    | 'margin'
    | 'margin-top'
    | 'margin-right'
    | 'margin-bottom'
    | 'margin-left'
    | 'padding'
    | 'padding-top'
    | 'padding-right'
    | 'padding-bottom'
    | 'padding-left'
    | 'font-size'
    | 'font-weight'
    | 'font-style'
    | 'font-family'
    | 'text-align'
    | 'text-decoration'
    | 'text-transform'
    | 'text-shadow'
    | 'line-height'
    | 'letter-spacing'
    | 'word-spacing'
    | 'white-space'
    // NOT Supported in renderers, but could be added in the future:
    // | 'display'
    // | 'position'
    // | 'left'
    // | 'right'
    // | 'top'
    // | 'bottom'
    // | 'width'
    // | 'height'
    // | 'min-width'
    // | 'min-height'
    // | 'max-width'
    // | 'max-height'
    // | 'z-index'
    // | 'flex-direction'
    // | 'flex-wrap'
    // | 'justify-content'
    // | 'align-items'
    // | 'align-content'
    // Moved from the above list
    // | 'background-image'
    // | 'background-size'
    // | 'background-position'
    // | 'background-repeat'
    // | 'background-attachment'
    // | 'overflow'
    // | 'overflow-x'
    // | 'overflow-y'
    ;

export type RenderableCSS = Partial<Record<RenderableCssProperty, string>>;
